// internal/git/pr.go
package git

import (
	"fmt"
	"strings"
)

// PrRequest describes a pull request to create.
type PrRequest struct {
	Title      string
	Body       string
	HeadBranch string
	BaseBranch string
	Reviewers  []string
	Labels     []string
	Draft      bool
}

// PrResponse holds the created PR details.
type PrResponse struct {
	URL     string
	HTMLURL string
	Number  int
}

// PRTaskSummary is a brief task status for PR body formatting.
type PRTaskSummary struct {
	Title  string
	Status string
}

// PRBodyInput holds data for formatting a PR body.
type PRBodyInput struct {
	TicketExternalID string
	TicketTitle      string
	ReviewNotes      string
	FailedTask       string
	FailureReason    string
	TaskSummaries    []PRTaskSummary
	IsPartial        bool
}

// FormatPRBody generates a formatted PR description.
func FormatPRBody(input PRBodyInput) string {
	var sb strings.Builder

	if input.IsPartial {
		sb.WriteString("## ⚠️ PARTIAL Implementation\n\n")
		sb.WriteString("This PR contains **partial** implementation. A human developer should review and complete the remaining work.\n\n")
	}

	fmt.Fprintf(&sb, "## %s: %s\n\n", input.TicketExternalID, input.TicketTitle)

	sb.WriteString("### Tasks\n\n")
	for _, t := range input.TaskSummaries {
		var icon string
		switch t.Status {
		case "done":
			icon = "✅"
		case "failed":
			icon = "❌"
		default:
			icon = "⏳" // pending, skipped, unknown status
		}
		fmt.Fprintf(&sb, "- %s %s — %s\n", icon, t.Title, t.Status)
	}

	if input.IsPartial && input.FailedTask != "" {
		fmt.Fprintf(&sb, "\n### Failed Task\n**%s**: %s\n", input.FailedTask, input.FailureReason)
		sb.WriteString("\nA human developer should complete the remaining tasks.\n")
	}

	if input.ReviewNotes != "" {
		fmt.Fprintf(&sb, "\n### Review Notes\n%s\n", input.ReviewNotes)
	}

	sb.WriteString("\n---\n🤖 *Generated by [Foreman](https://github.com/canhta/foreman)*\n")

	return sb.String()
}

// NewPRRequest creates a standard PR request.
func NewPRRequest(externalID, title, headBranch, baseBranch string, draft bool, reviewers []string) PrRequest {
	return PrRequest{
		Title:      fmt.Sprintf("[Foreman] %s: %s", externalID, title),
		HeadBranch: headBranch,
		BaseBranch: baseBranch,
		Draft:      draft,
		Reviewers:  reviewers,
		Labels:     []string{"foreman-generated"},
	}
}

// NewPartialPRRequest creates a PR request for partial implementations.
func NewPartialPRRequest(externalID, title, headBranch, baseBranch string, reviewers []string) PrRequest {
	return PrRequest{
		Title:      fmt.Sprintf("[Foreman] [PARTIAL] %s: %s", externalID, title),
		HeadBranch: headBranch,
		BaseBranch: baseBranch,
		Draft:      true,
		Reviewers:  reviewers,
		Labels:     []string{"foreman-generated", "partial"},
	}
}
